#------------------------------------------------------------------------------
# Kafka:
#------------------------------------------------------------------------------

Replicas: 3
Image: "solsson/kafka"
ImageTag: "0.11.0.1"
ImagePullPolicy: "IfNotPresent"
resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 1536Mi
  # requests:
  #   cpu: 100m
  #   memory: 1024Mi
Storage: "1Gi"
# StorageClass: default
DataDirectory: "/opt/kafka/data"

#------------------------------------------------------------------------------
# Zookeeper:
#------------------------------------------------------------------------------

zookeeper:
  servers: 3
  resources: {}
  heap: "1G"
  storage: "2Gi"
  # StorageClass: default
  serverPort: 2888
  leaderElectionPort: 3888
  clientPort: 2181
  imagePullPolicy: "IfNotPresent"
  tickTimeMs: 2000
  initTicks: 10
  syncTicks: 5
  clientCnxns: 60
  snapRetain: 3
  purgeHours: 1
  probeInitialDelaySeconds : 15
  probeTimeoutSeconds : 5
  antiAffinity : "hard"
  logLevel : "INFO"
